name: Scala CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
    - name: Setup OpenJDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18.0.1'
        distribution: 'oracle'
        cache: 'sbt'
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt test
